name: tests
on:
  push: { branches: ["master", "main"] }
  pull_request: { branches: "*" }

jobs:
  build_and_test:
    name: Build and test
    strategy:
      matrix:
        feature:
          - async_tokio
          - async_smol
          - sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --no-default-features --features ${{matrix.feature}} --color=always
        env:
          RUSTFLAGS: -Dwarnings
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --no-default-features --features ${{matrix.feature}}
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets--no-default-features --features ${{matrix.feature}} --color=always
        env:
          RUSTFLAGS: -Dwarnings

